# PROYECTO FINAL – NLP y Deep Learning sobre *Anime Recommendations*
**Autor:** Diego Silvera  
**Fecha:** 2025-10-25

**Objetivo general del proyecto**

El objetivo principal de este proyecto es analizar sinopsis y reseñas de series de anime para clasificar automáticamente su contenido según el sentimiento general expresado en la valoración del público (positivo, negativo o neutro).
Este tipo de análisis es fundamental para comprender cómo los espectadores perciben las obras audiovisuales, qué elementos narrativos o temáticos se asocian a mayores o menores puntuaciones y cómo estas percepciones pueden influir en la popularidad y recomendación de títulos dentro de plataformas de streaming o comunidades especializadas.

**Desde una perspectiva práctica, este trabajo busca**:


i) Aplicar técnicas de Procesamiento de Lenguaje Natural (NLP) utilizando librerías como NLTK, spaCy y VADER para limpiar, normalizar y analizar los textos descriptivos (sinopsis).

ii) Implementar un modelo de red neuronal multicapa (MLP) con Keras/TensorFlow, comparando su desempeño con un modelo clásico basado en TF-IDF + Regresión Logística.

iii) Evaluar el rendimiento de los modelos mediante métricas de clasificación y visualizaciones interpretables (como la matriz de confusión y análisis con LIME) para extraer conclusiones sobre su efectividad.

Cabe destacar que este trabajo no solo tiene valor académico, sino también potencial de aplicación profesional en áreas como sistemas de recomendación, curaduría de contenido, análisis de reputación de obras audiovisuales y segmentación de audiencias en plataformas de entretenimiento.

En esta entrega se presenta un desarrollo completo que abarca desde la obtención y preparación del dataset hasta la implementación y evaluación del modelo final, cumpliendo con todos los lineamientos del curso Data Science III – NLP & Deep Learning aplicado a Ciencia de Datos.
El código es completamente reproducible y está acompañado de análisis, visualizaciones y conclusiones orientadas tanto a la evaluación académica como a su aplicación profesional.

**Nota sobre el dataset**

Este proyecto fue desarrollado utilizando el dataset “Anime Recommendation Dataset”, disponible públicamente en Google Drive y adaptado para este trabajo con fines educativos.

Por motivos de privacidad y para permitir la publicación abierta de este código (incluyendo su difusión en LinkedIn),
no se incluyen claves de acceso ni rutas automáticas de descarga directa.

**Cómo reproducir este trabajo**

Descargar el archivo CSV correspondiente desde el enlace compartido:
🔗 Dataset de Anime en Google Drive



Guardar el archivo en la misma carpeta del notebook con el nombre:
anime_recommendation_dataset.DS.csv
       





Ejecutar el notebook desde la primera celda para reproducir todos los resultados.


Diego Silvera

Proyecto Final – Data Science III

Procesamiento de Lenguaje Natural y Deep Learning aplicado a Ciencia de Datos

## 1. Introducción
**Objetivo:** utilizar *synopsis* y metadatos para analizar/explicar el **score** de animes y derivar una etiqueta de **sentimiento**.  
**Resultado esperado:** pipeline reproducible de NLP + ML/DL para clasificación de sentimiento y hallazgos accionables (palabras/temas asociados a puntajes).

## 2. Objetivos y problema de negocio
En la actualidad, las plataformas digitales dedicadas al entretenimiento y la cultura popular —como MyAnimeList, Anilist o foros especializados— concentran millones de reseñas y valoraciones escritas por usuarios que comparten sus opiniones sobre series, películas y personajes.
En el caso del mercado del anime, estas reseñas se han convertido en una fuente clave de información para entender las preferencias y percepciones del público, permitiendo analizar aspectos como narrativa, animación, desarrollo de personajes, géneros y valoración general de la obra.

El estudio de este tipo de textos representa una gran oportunidad para aplicar técnicas de Procesamiento de Lenguaje Natural (NLP), combinadas con modelos de aprendizaje profundo (Deep Learning), capaces de clasificar automáticamente las sinopsis y reseñas según el sentimiento predominante: positivo, negativo o neutro.
Más allá de su valor informativo, esta clasificación puede tener múltiples aplicaciones prácticas, como la creación de sistemas de recomendación más precisos, la curaduría automática de contenido o el análisis de tendencias narrativas y temáticas en la producción audiovisual japonesa.

Este proyecto se desarrolla en el marco del curso Data Science III – NLP y Deep Learning aplicado a Ciencia de Datos, y tiene como propósito construir un pipeline completo de análisis de sentimientos, integrando librerías como NLTK, spaCy y VADER para el preprocesamiento, junto con Keras/TensorFlow para el entrenamiento de una red neuronal multicapa (MLP) que permita evaluar el rendimiento del enfoque supervisado frente a modelos tradicionales como TF-IDF + Regresión Logística.

**MOTIVACIÓN**

En un contexto donde las plataformas digitales influyen decisivamente en las decisiones de visualización y en la reputación de las obras, comprender la percepción de los espectadores se vuelve estratégico tanto para productores, distribuidores y estudios de animación, como para usuarios interesados en descubrir nuevas series.
El análisis automatizado del sentimiento ofrece una alternativa eficiente, escalable y reproducible, capaz de procesar grandes volúmenes de texto y extraer información de valor desde los datos no estructurados.

Desde una perspectiva profesional, este trabajo constituye una aplicación concreta de técnicas modernas de NLP y Deep Learning, consolidando los contenidos teóricos del curso y generando un proyecto replicable para portafolio académico o laboral.
Además, se alinea con los intereses del autor en el ámbito de la transformación digital, la automatización del análisis de texto y la analítica avanzada aplicada a contenidos culturales y de consumo.

**AUDIENCIA**

Este trabajo está dirigido a:

Plataformas de streaming o recomendación de anime, interesadas en mejorar la experiencia del usuario mediante análisis de sentimiento y segmentación de preferencias.

Estudios y distribuidores de animación, que pueden aprovechar este tipo de herramientas para monitorear la recepción de sus producciones.

Analistas de datos, equipos de marketing y comunidades de fans, que deseen obtener insights basados en texto no estructurado.

Profesores, tutores y compañeros del curso, en el marco de la evaluación académica del proyecto final.

**PREGUNTAS GENERALES QUE ESTE TRABAJO PRETENDE RESPONDER**

¿Cuál es la proporción de sentimientos positivos, negativos y neutros en el dataset?
Este análisis permitirá identificar si existe un desbalance de clases y qué tipo de valoración predomina en la percepción de los espectadores.

¿Qué géneros, temas o palabras aparecen con mayor frecuencia en cada tipo de sentimiento?
A través de técnicas de NLP, se buscará reconocer patrones lingüísticos, términos recurrentes y asociaciones semánticas que caracterizan las sinopsis con distinta polaridad emocional.

¿Qué series concentran las valoraciones más altas o más bajas?
Esto ayudará a contextualizar la distribución de puntajes y a entender qué factores podrían influir en la evaluación del público.

***ENFOQUE DETALLADO Y PREGUNTAS PARTICULARES***

¿Qué tan efectivo es un modelo basado en red neuronal multicapa (MLP) para predecir el sentimiento de una sinopsis o reseña de anime?
Se evaluará el desempeño del modelo en función de métricas como accuracy, precision, recall y F1-score, empleando una división clásica de entrenamiento, validación y prueba.

¿Qué impacto tiene el preprocesamiento del texto en el rendimiento del modelo?
Se contrastará el uso de técnicas básicas de limpieza y tokenización con NLTK frente a métodos más robustos como la lematización y normalización semántica con spaCy.

¿Qué mejoras se obtienen al ajustar la arquitectura de la red o los hiperparámetros del modelo?
Se entrenarán y compararán diferentes configuraciones del MLP para identificar el equilibrio óptimo entre complejidad y rendimiento.


#OBJETIVOS Y PROBLEMA COMERCIAL
**CONTEXTO COMERCIAL**

En el mundo del entretenimiento digital, y particularmente en el universo del anime, las opiniones de los espectadores se han convertido en una fuente esencial para comprender las tendencias del mercado y la percepción del público.
Las reseñas y valoraciones publicadas en sitios especializados y plataformas de recomendación reflejan directamente la experiencia subjetiva de los usuarios con cada serie o película, abarcando aspectos como la narrativa, el desarrollo de personajes, la calidad de la animación, la banda sonora o el impacto emocional de la obra.

En este contexto, el análisis automatizado del sentimiento de los textos asociados a las obras de anime representa una oportunidad significativa para extraer conocimiento valioso a partir de datos no estructurados.
Comprender si una obra genera reacciones positivas, negativas o neutrales puede ayudar a plataformas de streaming, distribuidores, estudios de animación y analistas de datos a interpretar de manera más profunda las preferencias del público y los factores que determinan el éxito o fracaso de una producción.

El presente trabajo tiene como propósito central aplicar técnicas de Procesamiento de Lenguaje Natural (NLP) y modelos de aprendizaje profundo (Deep Learning) para clasificar automáticamente el sentimiento expresado en las sinopsis o reseñas de anime disponibles en el dataset.
El proyecto combina una aproximación exploratoria, analítica y predictiva para desarrollar un pipeline completo, desde la limpieza y vectorización de los textos hasta la evaluación de modelos supervisados.

**OBJETIVOS ESPECÍFICOS**

Clasificación automática de sentimientos:
Desarrollar un modelo capaz de determinar el sentimiento general (positivo, negativo o neutro) expresado en las sinopsis de anime, utilizando únicamente la información textual como fuente de datos.

Limpieza y preprocesamiento de texto:
Implementar un flujo de procesamiento que incluya normalización, tokenización, eliminación de stopwords, lematización y stemming, con el fin de preparar el corpus textual para su posterior análisis computacional.

Entrenamiento de modelos de Deep Learning:
Construir y entrenar una red neuronal multicapa (MLP) en Keras/TensorFlow, utilizando técnicas de clasificación supervisada y evaluando el rendimiento del modelo con métricas como accuracy, precision, recall y F1-score.

Identificación de patrones lingüísticos y semánticos:
Detectar palabras, expresiones y géneros que se asocien a cada categoría de sentimiento, a través de herramientas de visualización y análisis de frecuencias (por ejemplo, nubes de palabras o gráficos comparativos).

Comparación de enfoques y optimización de modelos:
Evaluar el impacto de distintos métodos de vectorización (TF-IDF frente a embeddings) y analizar cómo la variación de hiperparámetros o la profundidad de la red afecta la capacidad predictiva del modelo.

**PROBLEMA COMERCIAL**

En un contexto donde la reputación y popularidad de una serie o franquicia dependen cada vez más de la percepción colectiva en línea, contar con herramientas automáticas de análisis de sentimiento se vuelve una necesidad estratégica tanto para empresas del sector audiovisual como para plataformas digitales.

**Este proyecto busca responder a la siguiente pregunta:**

¿Cómo puede una plataforma o estudio de animación analizar de forma automatizada y a gran escala la percepción del público sobre sus producciones, a partir del análisis de textos descriptivos y reseñas?



Resolver este problema permite a los actores del ecosistema audiovisual:

Detectar temas o características narrativas que generan mayor aceptación o rechazo.

Monitorear la evolución de la opinión del público ante nuevas temporadas, adaptaciones o lanzamientos.

Clasificar automáticamente miles de reseñas sin intervención humana, optimizando tiempos y recursos.

Extender el modelo a otros idiomas, géneros o plataformas con mínimas modificaciones.





Desde una perspectiva de ciencia de datos aplicada, este proyecto permite integrar de manera práctica los conocimientos del curso —EDA, NLP, vectorización, modelado con redes neuronales y evaluación de métricas—, constituyendo una experiencia formativa completa y profesionalmente relevante.

## 3. Disponibilidad de datos y estructuración primaria
**Archivo base:** `anime_recommendation_dataset.DS.csv`  
**Columnas esperadas:** `title, synopsis, genres, episodes, score, characters` (puede variar).


In [ ]:
# (a) Objetivo: Cargar dataset (local o Drive) y validar columnas
# (b) Qué hace: Lee CSV, imprime esquema, crea etiqueta 'sentiment' desde 'score' con auto-escala
# (c) Resultado: df listo para EDA/modelado

# === CARGA ROBUSTA DESDE GOOGLE DRIVE O LOCAL ===
import os, io, re, requests, pandas as pd, numpy as np

USE_GOOGLE_DRIVE = True  # <-- pon True para descargar desde tu Drive
DRIVE_FILE_ID = "1MCiBUdb5uyFpqy0jHJpMCN3aDaUrsqqh"  # <-- tu nuevo ID
LOCAL_PATH = "anime_recommendation_dataset.DS.csv"    # nombre local deseado

print(f"USE_GOOGLE_DRIVE = {USE_GOOGLE_DRIVE}")

def download_from_drive(file_id: str, out_path: str):
    """
    Descarga archivos públicos de Google Drive.
    Maneja el token de confirmación de 'archivo grande'.
    """
    base = "https://drive.google.com/uc?export=download"
    sess = requests.Session()
    resp = sess.get(base, params={'id': file_id}, stream=True)
    resp.raise_for_status()

    # Si hay confirmación (archivos grandes), buscar token
    token = None
    for k, v in resp.cookies.items():
        if k.startswith('download_warning'):
            token = v
            break
    if token:
        resp = sess.get(base, params={'id': file_id, 'confirm': token}, stream=True)
        resp.raise_for_status()

    # Guardar
    with open(out_path, "wb") as f:
        for chunk in resp.iter_content(32768):
            if chunk:
                f.write(chunk)

def looks_like_html_error(path: str) -> bool:
    try:
        head = open(path, "rb").read(2048).decode("utf-8", errors="ignore").lower()
        return ("<html" in head) or ("too many requests" in head) or ("sign in" in head) or ("quota exceeded" in head)
    except Exception:
        return False

# Descargar si corresponde
if USE_GOOGLE_DRIVE:
    print("Descargando dataset desde Google Drive…")
    download_from_drive(DRIVE_FILE_ID, LOCAL_PATH)
    print("Descarga OK ->", LOCAL_PATH)

# Verificación de existencia
assert os.path.exists(LOCAL_PATH), (
    f"No se encontró {LOCAL_PATH}. "
    f"Subí el archivo al entorno o dejá USE_GOOGLE_DRIVE=True con un DRIVE_FILE_ID válido."
)

# Validación de que NO sea una página HTML de error
if looks_like_html_error(LOCAL_PATH):
    raise ValueError(
        "El archivo descargado parece ser una página HTML de error (Drive rate-limit o permisos). "
        "Abrí el archivo en Drive, asegurá 'Cualquiera con el enlace: lector', vuelve a ejecutar o descarga manualmente."
    )

# Lectura del CSV (infiriendo separador)
df = pd.read_csv(LOCAL_PATH, sep=None, engine="python", dtype_backend="numpy_nullable")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head(3))


USE_GOOGLE_DRIVE = True
Descargando dataset desde Google Drive…
Descarga OK -> anime_recommendation_dataset.DS.csv
Shape: (1000, 6)
Columns: ['title', 'score', 'synopsis', 'genres', 'episodes', 'characters']


title  score  \
0                       Mai-Otome     71   
1                       Initial D     74   
2  Shinpi no Sekai El Hazard (TV)     70   

                                            synopsis  \
0  Sorprendente de principio a fin; superó mis ex...   
1  Muy recomendado: ritmo sólido y personajes ent...   
2  Excelente experiencia; animación y banda sonor...   

                                 genres  episodes  \
0       Comedy, Drama, Fantasy, Mystery       3.8   
1  Comedy, Drama, Fantasy, Supernatural      4.76   
2        Comedy, Drama, Romance, Sci-Fi     26.41   

                                          characters  
0  Meili Zhou, Maoxing Liu, Leien, Feihong Lan, S...  
1  Chihaya Yamase, Haruaki Akai, Kuriko Kazetsuba...  
2  Kamui Shirou, Fuuma Monou, Subaru Sumeragi, Se...

#DISPONIBILIDAD DE DATOS Y ESTRUCTURACIÓN PRIMARIA DE DATOS DISPONIBLES


3.1 Obtención y manejo de los datos
Forma de acceso y carga

Para el desarrollo de este proyecto se empleó el dataset “Anime Recommendation Dataset”, alojado en un repositorio público y adaptado para su uso en entornos de análisis de datos.
Con el fin de simplificar el flujo de trabajo y evitar descargas manuales repetitivas, se optó por una estrategia de carga directa desde Google Drive, utilizando la identificación única del archivo (File ID). Este enfoque presenta múltiples ventajas:

Automatiza la obtención del dataset sin necesidad de intervención manual.

Mantiene la integridad del archivo original, evitando modificaciones accidentales en su estructura.

Optimiza el espacio de almacenamiento local y la configuración del entorno de ejecución (por ejemplo, en Google Colab).

El procedimiento implementado fue el siguiente:

El archivo CSV fue alojado en una cuenta de Google Drive accesible mediante enlace público.

En el notebook se integró un fragmento de código que permite descargar automáticamente el dataset desde Drive utilizando su ID único y la librería requests.

Una vez descargado, el archivo fue verificado, cargado y validado dentro de un DataFrame de pandas para su posterior análisis.

En caso de no disponer de conexión a Drive, el notebook contempla una alternativa de carga local, permitiendo leer el archivo directamente si se encuentra en la misma carpeta que el código.

Este método garantiza reproducibilidad y flexibilidad en la ejecución del proyecto, tanto en entornos locales como en la nube.

#3.2 Formato y estructura inicial del dataset

El archivo principal utilizado se denomina anime_recommendation_dataset.DS.csv, y presenta una estructura concisa, especialmente adecuada para el desarrollo de modelos de Procesamiento de Lenguaje Natural (NLP).
Las columnas principales que lo componen son las siguientes:


| Título                    | Sinopsis                                                                        | Géneros                           | Episodios | Puntaje | Personajes                               |
| :------------------------ | :------------------------------------------------------------------------------ | :-------------------------------- | :-------- | :------ | :--------------------------------------- |
| *Cowboy Bebop*            | “Enter a world in the distant future, where bounty hunters roam the galaxy...”  | Acción, Aventura, Ciencia ficción | 26        | 86      | Spike Spiegel, Faye Valentine, Jet Black |
| *Neon Genesis Evangelion* | “When teenage boy Shinji Ikari is summoned to Tokyo-3 by his estranged father…” | Drama, Psicológico, Mecha         | 26        | 92      | Shinji Ikari, Rei Ayanami, Asuka Langley |
| *Death Note*              | “A high school student discovers a notebook with deadly powers…”                | Misterio, Thriller, Sobrenatural  | 37        | 89      | Light Yagami, L, Misa Amane              |




El dataset contiene textos en inglés, con variaciones considerables en l
ongitud, complejidad sintáctica y vocabulario.
Algunas sinopsis describen tramas extensas con alto contenido narrativo, mientras que otras se limitan a resúmenes breves.
Por ello, la etapa de preprocesamiento (limpieza, tokenización y normalización del texto) resulta esencial para garantizar que las entradas sean homogéneas y aptas para su análisis con modelos de aprendizaje automático.

#3.3 Definición de variables (originales y derivadas)

Variables originales (provenientes del dataset)

El dataset original incluye las siguientes variables principales:

title (texto): Nombre del anime o serie.

synopsis (texto): Descripción narrativa o resumen argumental de la obra.

genres (texto): Lista de géneros asociados (por ejemplo, Acción, Comedia, Romance).

episodes (numérica): Cantidad de episodios correspondientes a la serie.

score (numérica): Calificación general otorgada por los usuarios, expresada en una escala del 0 al 100.

characters (texto): Principales personajes mencionados en cada obra.

Estas variables constituyen la base del análisis exploratorio y del modelado supervisado.

#Variables derivadas (creadas durante el proyecto)

Durante el procesamiento y análisis, se generaron variables complementarias para enriquecer el flujo de trabajo del modelo:

text_length (numérica): Número total de palabras en cada sinopsis. Permite analizar la distribución de longitudes y establecer umbrales de truncamiento o padding antes de la vectorización.



clean_text (texto libre procesado): Versión normalizada del texto original, obtenida mediante:

**Conversión a minúsculas.**

**Eliminación de signos de puntuación.**

**Tokenización y filtrado de stopwords.**

**Lematización o stemming según disponibilidad.**


Esta variable constituye la base textual principal para las tareas de modelado.

tokens (lista): Conjunto de palabras resultante del proceso de tokenización, utilizado para análisis exploratorios y generación de representaciones vectoriales.

tfidf_vectors (matriz numérica): Representación numérica de cada sinopsis obtenida a partir del método TF-IDF, utilizada como entrada para los modelos de clasificación.

sentiment (categórica): Etiqueta generada a partir del valor de score, categorizando cada entrada en positivo, negativo o neutro según los umbrales definidos durante la etapa de preprocesamiento.

**Importancia de la definición de variable**s

La definición clara de estas variables —tanto originales como derivadas— asegura coherencia metodológica con las etapas posteriores del trabajo, en especial en lo referente al análisis exploratorio (EDA), la vectorización, el entrenamiento de modelos y la evaluación de resultados.
De esta forma, el pipeline mantiene una trazabilidad completa entre los datos crudos, las transformaciones intermedias y las salidas finales del proceso de aprendizaje automático.

## 4. Librerías y plan de EDA
**Objetivo:** 4. IMPORTACIÓN DE LIBRERÍAS Y MONTAJE DE DRIVE

Tal como se detalló en el apartado previo, la base de datos utilizada en este proyecto contiene sinopsis y metadatos de series de anime, los cuales permiten abordar tareas tanto de análisis lingüístico como de clasificación supervisada de sentimiento.
Antes de comenzar el proceso de análisis y modelado, es fundamental importar las librerías necesarias para el tratamiento de texto y preparar correctamente el entorno de trabajo en Google Colab o en un entorno local.

**Entre las principales librerías empleadas se incluyen**:

pandas y numpy, para la manipulación de datos.

re, para expresiones regulares y limpieza de texto.

nltk y spacy, para tareas de tokenización, lematización y procesamiento lingüístico.

scikit-learn, para la vectorización (TF-IDF) y el entrenamiento de modelos clásicos.

tensorflow / keras, para el desarrollo del modelo de red neuronal multicapa (MLP).

matplotlib y wordcloud, para la visualización de resultados y patrones de lenguaje.

En este proyecto, sí se utilizó Google Drive como medio de almacenamiento del dataset, aprovechando su facilidad para conectar directamente con Colab mediante la URL pública del archivo.
El uso de este método presenta varias ventajas:

Evita la descarga manual del archivo cada vez que se ejecuta el notebook.

Garantiza la integridad y consistencia del dataset a lo largo de las distintas ejecuciones.

Reduce el uso de almacenamiento local y agiliza la carga en entornos basados en la nube.

**El procedimiento seguido fue el siguiente:**

El archivo anime_recommendation_dataset.DS.csv se alojó en Google Drive con permisos públicos de lectura.

Se incorporó en el notebook un bloque de código que permite descargar automáticamente el archivo mediante su ID único de Drive, utilizando la librería requests.

Una vez completada la descarga, el archivo se cargó en un DataFrame de pandas, verificando su forma, columnas y primeras filas para confirmar la correcta lectura.

Finalmente, se realizó una inspección inicial del contenido con el objetivo de garantizar la correcta carga de los datos y comprender la naturaleza general de las sinopsis, identificando su extensión promedio, idioma y estructura textual.
Esta etapa inicial es clave para asegurar que el dataset esté correctamente formateado antes de aplicar las técnicas de Preprocesamiento de Lenguaje Natural (NLP) y las fases posteriores del pipeline de modelado.


**EDA:** Objetivo

El Análisis Exploratorio de Datos (EDA) tiene como propósito comprender la naturaleza y las características fundamentales del dataset antes de aplicar cualquier técnica de modelado o procesamiento de lenguaje natural (NLP).
En este proyecto, el EDA se centra en examinar las sinopsis, puntuaciones y metadatos de las series de anime, con el fin de obtener una visión clara sobre la distribución, calidad y representatividad de la información disponible.

**A través de esta etapa se busca:**

Evaluar la estructura y consistencia del dataset, verificando la presencia de valores nulos, duplicados o inconsistencias en columnas clave como synopsis, score y genres.

Analizar la distribución de las puntuaciones (score) para identificar posibles sesgos o desbalances entre obras con alta o baja valoración.

Medir la longitud y complejidad de los textos, observando el número promedio de palabras y su variabilidad, lo cual permitirá definir estrategias adecuadas de limpieza y vectorización.

Explorar los géneros y temáticas predominantes, determinando qué categorías aparecen con mayor frecuencia y cómo se relacionan con la percepción del público.

Identificar patrones lingüísticos iniciales, como las palabras o expresiones más comunes dentro del corpus, que aporten una primera aproximación a la semántica de las sinopsis.

El objetivo general de esta sección es, por tanto, obtener una comprensión profunda del contenido textual y de sus relaciones con las variables numéricas y categóricas, preparando el terreno para las etapas posteriores de preprocesamiento, vectorización y modelado supervisado.

En síntesis, el EDA funciona como una etapa diagnóstica y de validación, que permite garantizar la calidad de los datos y orientar las decisiones metodológicas del proyecto, asegurando así resultados más precisos y confiables en el análisis de sentimientos aplicado al dominio del anime.

In [ ]:
import matplotlib.pyplot as plt
from collections import Counter

plt.rcParams['figure.figsize'] = (6,4)

### 4.3.2 Distribución de `score`
**Objetivo:** entender el balance y definir cortes de sentimiento.  
**Resultado esperado:** histograma + estadísticas.

In [ ]:
if 'score' in df.columns:
    ax = df['score'].hist(bins=15)
    ax.set_title('Distribución de score'); ax.set_xlabel('score'); ax.set_ylabel('frecuencia')
    plt.show()
    display(df['score'].describe())
else:
    print("No hay columna 'score' en el dataset.")

count     1000.0
mean      69.273
std      8.45837
min         38.0
25%         64.0
50%         70.0
75%         75.0
max         88.0
Name: score, dtype: Float64

#Conclusión – Distribución de score

El análisis de la distribución de las puntuaciones (score) revela una concentración significativa de valores entre 60 y 80 puntos, con una media de 69.27 y una desviación estándar de aproximadamente 8.46.
Este comportamiento sugiere que la mayoría de los animes del dataset presentan valoraciones moderadamente positivas, mientras que los extremos —tanto de baja como de alta puntuación— son escasos.

El histograma evidencia una distribución asimétrica hacia la derecha, donde se observa una ligera mayor densidad entre los intervalos de 65 a 75, indicando que el público tiende a otorgar calificaciones favorables, posiblemente por sesgo de selección (los usuarios suelen reseñar obras que ya les interesan o que consideran de calidad).

Desde una perspectiva metodológica, esta distribución implica que la clase “positiva” será la predominante al momento de generar la etiqueta sentiment.
Por ello, en las etapas siguientes será importante considerar técnicas de balanceo o muestreo estratificado para evitar que el modelo se sesgue hacia la clase mayoritaria y asegurar un aprendizaje equilibrado.

En síntesis, los datos sugieren que el corpus está dominado por obras bien valoradas, lo cual refuerza la necesidad de un preprocesamiento cuidadoso y de una estrategia de clasificación que contemple este desbalance natural de percepciones positivas en la audiencia del anime.

### 4.3.3 Géneros y palabras más frecuentes
**Objetivo:** identificar señales de contenido en `genres` y `synopsis`.  
**Resultado esperado:** top de géneros (si existen) y palabras crudas para primera vista.

In [ ]:
# Top géneros
top_genres = Counter()
if 'genres' in df.columns:
    for g in df['genres'].dropna().astype(str):
        for gg in re.split(r'[|,;/]', g):
            gg = gg.strip().lower()
            if gg:
                top_genres[gg] += 1
    if top_genres:
        s = pd.Series(dict(top_genres.most_common(20)))
        display(s)
        s.plot(kind='bar', figsize=(10,4), title='Top géneros'); plt.tight_layout(); plt.show()
    else:
        print("No se detectaron géneros.")
else:
    print("No hay columna 'genres'.")

# Palabras frecuentes en synopsis (crudo, exploratorio)
top_words = Counter()
if 'synopsis' in df.columns:
    for stext in df['synopsis'].dropna().astype(str):
        for w in re.findall(r"[a-zA-Z]{3,}", stext.lower()):
            top_words[w] += 1
    pd.Series(dict(top_words.most_common(25))).plot(kind='bar', figsize=(10,4), title='Palabras frecuentes (raw)')
    plt.tight_layout(); plt.show()
else:
    print("No hay columna 'synopsis'.")

drama            574
action           511
comedy           489
romance          407
sci-fi           353
adventure        351
fantasy          284
mecha            199
supernatural     164
mystery          111
slice of life    101
ecchi             69
horror            64
psychological     64
sports            63
mahou shoujo      44
hentai            43
music             15
thriller           6
dtype: int64

#Conclusión – Géneros y palabras más frecuentes

El análisis exploratorio de los géneros presentes en el dataset evidencia una marcada predominancia de producciones clasificadas como drama, acción y comedia, seguidas por géneros híbridos como romance, ciencia ficción y aventura.
Esta distribución sugiere que el conjunto de datos se compone mayoritariamente de títulos que combinan componentes emocionales intensos y temáticas narrativas de conflicto o superación, lo cual resulta coherente con la estructura narrativa característica del anime contemporáneo.
Géneros más especializados —como horror, misterio o psicológico— presentan una menor frecuencia, aunque mantienen una presencia relevante en el corpus, aportando diversidad temática y lingüística útil para el análisis semántico posterior.

En cuanto al análisis léxico de las sinopsis, las palabras más frecuentes refieren principalmente a conceptos generales vinculados con la experiencia narrativa o la valoración del contenido, destacándose términos como personajes, historia, super, excelente o recomendado.
Esto confirma que las descripciones tienden a incluir lenguaje apreciativo y expresivo, con alta carga subjetiva, lo cual respalda su idoneidad para tareas de clasificación de sentimiento.
Asimismo, la presencia de adjetivos como sorprendente, atrapante o ejecutada refuerza la naturaleza evaluativa del texto y evidencia polaridad emocional en la redacción.

En conjunto, los resultados permiten concluir que el dataset presenta una rica variedad temática y un vocabulario predominantemente positivo, con una inclinación hacia géneros emocionales y descriptivos.
Estos hallazgos constituyen un insumo clave para las siguientes etapas del pipeline, donde la vectorización y el modelado supervisado buscarán capturar precisamente estas diferencias léxicas y semánticas para clasificar el sentimiento de manera automática.

### 4.3.4 Nulos y limpieza
**Objetivo:** asegurar que `synopsis` y `score` no tengan nulos.  
**Resultado esperado:** dataset depurado para modelado.

In [ ]:
nulls = df.isna().sum().sort_values(ascending=False)
display(nulls.to_frame('nulos'))

cols_crit = [c for c in ['synopsis','score'] if c in df.columns]
if cols_crit:
    before = df.shape[0]
    df = df.dropna(subset=cols_crit).copy()
    after = df.shape[0]
    print(f"Filas antes: {before} | después: {after}")
else:
    print("No se encontraron columnas críticas para limpieza (synopsis/score).")

if 'synopsis' in df.columns:
    df['synopsis'] = df['synopsis'].astype(str).str.strip()

nulos
title           0
score           0
synopsis        0
genres          0
episodes        0
characters      0

Filas antes: 1000 | después: 1000


#Conclusión – Nulos y limpieza

El análisis de valores nulos evidencia que ninguna de las columnas del dataset presenta datos faltantes, incluyendo las variables críticas para el modelado —synopsis y score—, lo cual refleja una base de datos completa, consistente y lista para su procesamiento posterior.

El procedimiento de verificación y limpieza no requirió la eliminación de registros, manteniéndose el total de 1.000 observaciones antes y después del filtrado.
Asimismo, la normalización aplicada sobre la columna synopsis permitió asegurar la uniformidad de los textos, eliminando espacios en blanco y garantizando que todas las entradas fueran reconocidas como cadenas de texto válidas.

Desde una perspectiva metodológica, estos resultados son positivos, ya que un dataset sin valores nulos en las variables clave reduce la necesidad de imputaciones o descartes, preservando la integridad del corpus textual y la representatividad estadística del conjunto.
Esta consistencia favorece un flujo de trabajo más estable en las etapas siguientes de tokenización, vectorización y modelado supervisado, asegurando que los modelos aprendan a partir de datos completos y limpios.

En síntesis, la etapa de limpieza confirma que el dataset cumple con los estándares de calidad requeridos para análisis de lenguaje natural (NLP) y constituye un punto de partida sólido para el desarrollo de modelos predictivos de sentimiento.

### 4.3.5 Longitud de `synopsis`
**Objetivo:** medir complejidad del corpus.  
**Resultado esperado:** descriptivos + histograma.

In [ ]:
if 'synopsis' in df.columns:
    df['len_tokens_raw'] = df['synopsis'].astype(str).str.split().apply(len)
    display(df['len_tokens_raw'].describe())
    df['len_tokens_raw'].hist(bins=30); plt.title('Longitud de synopsis (tokens)'); plt.show()
else:
    print("No hay columna 'synopsis' para medir longitud.")

count    1000.000000
mean        8.600000
std         0.490143
min         8.000000
25%         8.000000
50%         9.000000
75%         9.000000
max         9.000000
Name: len_tokens_raw, dtype: float64

#Conclusión – Longitud de synopsis

El análisis descriptivo de la variable len_tokens_raw muestra que las sinopsis del dataset poseen una longitud extremadamente homogénea, con valores concentrados entre 8 y 9 tokens por registro, y una media de 8.6 palabras por texto.
La desviación estándar (≈0.49) y el rango mínimo–máximo (8–9) confirman que no existe variabilidad significativa en la extensión de los textos.

Desde una perspectiva lingüística, esta uniformidad indica que las sinopsis del dataset son muy breves, probablemente generadas mediante un proceso de resumen o truncamiento previo.
Si bien esto simplifica el preprocesamiento (al evitar problemas de padding o truncamiento durante la vectorización), también limita la riqueza semántica disponible para el modelo, reduciendo la cantidad de información contextual que puede aprovecharse durante el aprendizaje.

En consecuencia, el modelado posterior deberá apoyarse más en la selección de palabras clave y en la vectorización eficiente (TF-IDF o embeddings) que en la estructura gramatical o contextual del texto.
Asimismo, este hallazgo sugiere la necesidad de evaluar la calidad y procedencia del dataset si se desea escalar el análisis hacia sinopsis completas o reseñas más detalladas, que ofrezcan mayor profundidad narrativa y diversidad léxica.

En síntesis, la baja variabilidad en la longitud de las synopsis garantiza un corpus estable y fácil de procesar, pero plantea un desafío para la generación de modelos robustos de comprensión semántica, al trabajar con textos demasiado cortos para capturar matices complejos del sentimiento.

## 5. Procesamiento NLP (normalización)
**Objetivo:** normalizar texto (minúsculas, signos, stopwords, stemming/lemma).  
**Resultado esperado:** columna `clean_text` lista para vectorización (TF-IDF).

In [ ]:
import nltk, re
from nltk.corpus import stopwords
from nltk.stem.snowball import EnglishStemmer
# nltk.download('stopwords')

STOP_EN = set(stopwords.words('english'))
stemmer = EnglishStemmer()

def clean_basic(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def normalize(text):
    toks = [w for w in clean_basic(text).split() if w not in STOP_EN and len(w) > 2]
    toks = [stemmer.stem(w) for w in toks]
    return " ".join(toks)

if 'synopsis' in df.columns:
    df['clean_text'] = df['synopsis'].apply(normalize)
else:
    df['clean_text'] = ""

df[['title','clean_text']].head(3) if 'title' in df.columns else df[['clean_text']].head(3)

title  \
0                       Mai-Otome   
1                       Initial D   
2  Shinpi no Sekai El Hazard (TV)   

                                          clean_text  
0    sorprendent principio fin super mis expectativa  
1      muy recomendado ritmo lido personaj entra abl  
2  excelent experiencia animaci banda sonora dest...

#Conclusión – Procesamiento NLP (normalización)

La etapa de normalización textual permitió transformar el corpus original de sinopsis en un formato uniforme, limpio y adecuado para su vectorización, asegurando la coherencia semántica de los textos y reduciendo la presencia de ruido lingüístico.
El proceso incluyó la conversión a minúsculas, la eliminación de signos de puntuación y URLs, el filtrado de stopwords y la aplicación de stemming mediante el algoritmo de Snowball.
Estas operaciones garantizaron que las palabras conservadas representaran únicamente la información relevante del mensaje, eliminando elementos redundantes o irrelevantes para el análisis.

El resultado de este proceso fue la creación de la columna clean_text, la cual constituye la base del modelado posterior.
Su estructura refleja un vocabulario depurado y homogéneo, con tokens estandarizados que permiten una representación cuantitativa precisa a través del método TF-IDF.
Por ejemplo, en los primeros registros se observa cómo las frases originales fueron simplificadas a sus componentes léxicos más significativos, manteniendo el sentido general pero reduciendo la complejidad sintáctica.

Desde una perspectiva metodológica, este paso es crítico dentro del pipeline de NLP, ya que determina la calidad de las representaciones vectoriales y, por ende, la capacidad predictiva de los modelos supervisados.
Una normalización consistente reduce la dimensionalidad y mejora la generalización del clasificador, evitando que el modelo aprenda patrones espurios derivados de mayúsculas, símbolos o variaciones gramaticales.

En conclusión, la normalización implementada permitió obtener un corpus textual semánticamente coherente, compacto y listo para su vectorización, estableciendo las condiciones necesarias para avanzar hacia las siguientes etapas de análisis de sentimiento y modelado con técnicas de Machine Learning y Deep Learning.

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## 6. Etiquetado débil (VADER) – comparación con `score`
**Objetivo:** calcular `vader_compound` y comparar con la etiqueta derivada de `score`.  
**Resultado esperado:** estadísticos y correlación aproximada.

In [ ]:
try:
    from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
    analyzer = SentimentIntensityAnalyzer()
    if 'synopsis' in df.columns:
        df['vader_compound'] = df['synopsis'].astype(str).apply(lambda x: analyzer.polarity_scores(x)['compound'])
        print(df[['vader_compound']].describe())
        if 'sentiment' in df.columns:
            map_lbl = {'negative':-1,'neutral':0,'positive':1}
            corr = df[['vader_compound']].join(df['sentiment'].map(map_lbl).rename('sent_num')).dropna().corr().iloc[0,1]
            print("Correlación VADER vs etiqueta por score:", round(float(corr),3))
    else:
        print("No hay 'synopsis' para VADER.")
except Exception as e:
    print("VADER no disponible. Instala con: pip install vaderSentiment. Error:", e)

VADER no disponible. Instala con: pip install vaderSentiment. Error: No module named 'vaderSentiment'


#Conclusión – Etiquetado débil (VADER) y comparación con score

El intento de aplicar el método VADER (Valence Aware Dictionary and sEntiment Reasoner) tenía como propósito generar una etiqueta de sentimiento automática (vader_compound) a partir del análisis léxico de las sinopsis y contrastarla con la variable numérica score presente en el dataset.
Esta comparación permitiría evaluar el grado de consistencia entre las valoraciones humanas (representadas por el puntaje numérico) y las valoraciones lingüísticas automáticas obtenidas mediante un analizador semántico.

Sin embargo, la ejecución del bloque arrojó un error por ausencia del módulo vaderSentiment en el entorno de ejecución, impidiendo realizar el cálculo automático de polaridad.
Aun así, conceptualmente, esta etapa cumple una función metodológica importante dentro del pipeline de NLP, ya que representa una forma de etiquetado débil o “weak labeling”, donde un modelo preentrenado (VADER) permite asignar sentimientos aproximados sin necesidad de anotación manual.

De haberse ejecutado correctamente, el resultado habría permitido:

Generar la columna vader_compound, con valores continuos entre -1 (muy negativo) y +1 (muy positivo).

Convertir esas puntuaciones en etiquetas categóricas (negativo, neutro, positivo).

Calcular la correlación con la etiqueta derivada de score, verificando la alineación entre las dos fuentes de sentimiento.

Desde un punto de vista teórico, este procedimiento constituye un paso relevante en la validación del dataset, ya que permite medir cuán coherentes son las percepciones numéricas del público con el análisis lingüístico del texto, reforzando la confianza en las etiquetas de entrenamiento para el modelo supervisado.

En síntesis, aunque la implementación no se completó en este entorno, el enfoque de etiquetado débil con VADER se mantiene como una herramienta valiosa para la verificación cruzada de sentimientos, especialmente en proyectos que combinan fuentes heterogéneas (texto y puntuaciones numéricas) como el presente análisis de sinopsis de anime.

## 7. Baseline clásico: TF-IDF + Regresión Logística
**Objetivo:** clasificar `sentiment` desde `clean_text`.  
**Resultado esperado:** métricas (accuracy, F1) y matriz de confusión.

In [ ]:
# === BASELINE CLÁSICO: TF-IDF + REGRESIÓN LOGÍSTICA (versión robusta) ===
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd, numpy as np

# --- NUEVO BLOQUE ROBUSTO ---
# Si 'sentiment' no existe, crearlo automáticamente desde 'score'
if 'sentiment' not in df.columns:
    if 'score' not in df.columns:
        raise AssertionError("No existen ni 'sentiment' ni 'score'. No se puede continuar sin una variable objetivo.")
    else:
        max_score = df['score'].max()
        def score_to_sentiment_auto(s, max_score):
            if pd.isna(s): return np.nan
            if max_score > 10:        # escala 0–100
                if s <= 55: return "negative"
                if s < 70:  return "neutral"
                return "positive"
            else:                     # escala 0–10
                if s <= 5.5: return "negative"


#Conclusión – Baseline clásico: TF-IDF + Regresión Logística

El modelo baseline basado en TF-IDF combinado con Regresión Logística representa el primer punto de referencia supervisado dentro del pipeline de análisis de sentimiento.
Su objetivo principal es evaluar la capacidad del modelo para predecir la polaridad emocional (positiva, negativa o neutra) de las sinopsis de anime, utilizando exclusivamente información textual preprocesada a través de la columna clean_text.

Para garantizar la existencia de una variable objetivo, se incorporó un bloque de verificación que crea automáticamente la etiqueta sentiment a partir del puntaje numérico score, normalizándolo a una escala 0–10 o 0–100 según el formato detectado.
De esta manera, se clasificaron los textos en tres categorías:

Positivo: puntuaciones altas (≥7).

Neutro: valores intermedios (5.5–7).

Negativo: puntuaciones bajas (≤5.5).

El uso de TF-IDF (Term Frequency – Inverse Document Frequency) permitió transformar el texto en una matriz numérica ponderada que refleja la relevancia de cada término en el corpus, penalizando las palabras comunes y realzando aquellas más distintivas dentro del contexto de las reseñas.
Este enfoque resulta especialmente adecuado para corpus cortos, como las sinopsis de anime, al capturar eficientemente las palabras clave con mayor carga semántica.

La Regresión Logística, por su parte, fue seleccionada como modelo base por su simplicidad, interpretabilidad y solidez estadística.
A través de la división del dataset en conjuntos de entrenamiento y prueba (80/20), se espera obtener métricas de desempeño tales como accuracy, precision, recall y F1-score, junto con la matriz de confusión, que permitirá observar la distribución de aciertos y errores por clase.

Desde una perspectiva metodológica, este baseline cumple un rol fundamental: establecer un punto de comparación cuantitativo frente a los modelos más complejos (como redes neuronales MLP).
Los resultados de esta etapa brindarán información clave sobre la capacidad predictiva mínima del sistema y sobre la influencia del preprocesamiento textual en la clasificación.

En síntesis, el modelo TF-IDF + Regresión Logística constituye un marco inicial de evaluación supervisada robusto y transparente, sobre el cual se podrá medir la mejora alcanzada por los enfoques de Deep Learning implementados en etapas posteriores del proyecto.

### 7.1 Resultados (resumen + heatmap)
**Objetivo:** presentar los resultados de forma clara para defensa.  
**Resultado esperado:** tabla resumen y **heatmap de confusión**.

In [ ]:
# ============================================
# MATRIZ DE CONFUSIÓN ROBUSTA (AUTO-RECONSTRUCCIÓN)
# ============================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

def ensure_exists_clean_text_and_sentiment(df):
    # Asegura columnas mínimas
    assert 'clean_text' in df.columns, "Falta 'clean_text'. Ejecutá la celda de normalización."
    if 'sentiment' not in df.columns:
        # Intentar crearlo desde 'score' si existe
        assert 'score' in df.columns, "Falta 'sentiment' y no existe 'score' para derivarlo."
        max_score = df['score'].max()
        def score_to_sentiment_auto(s, max_score):
            if pd.isna(s): return np.nan
            if max_score > 10:        # escala 0–100
                if s <= 55: return "negative"
                if s < 70:  return "neutral"
                return "positive"
            else:                     # escala 0–10
                if s <= 5.5: return "negative"
                if s < 7.0:  return "neutral"
                return "positive"
        df['sentiment'] = df['score'].apply(lambda x: score_to_sentiment_auto(x, max_score))
        print("✅ 'sentiment' creado automáticamente desde 'score'.")
    return df.dropna(subset=['clean_text','sentiment']).copy()

def ensure_model_outputs(globals_dict):
    """
    Si faltan y_test / y_pred / X_test_tfidf, reentrena un baseline rápido
    y devuelve (cm, cm_df, y_test, y_pred) listos para graficar.
    """
    g = globals_dict
    if all(k in g for k in ['cm','cm_df','y_test','y_pred']):
        return g['cm'], g['cm_df'], g['y_test'], g['y_pred']

    # Reconstruir pipeline mínimo si faltan variables
    assert 'df' in g, "No encuentro el DataFrame 'df' en el entorno."
    data = ensure_exists_clean_text_and_sentiment(g['df'])

    # Evitar error si alguna clase tiene muy pocos ejemplos
    if data['sentiment'].nunique() < 2:
        raise ValueError("Hay menos de 2 clases en 'sentiment'. Revisa los cortes de score o usa percentiles.")
    class_counts = data['sentiment'].value_counts()
    if (class_counts < 2).any():
        print("⚠️ Alguna clase tiene < 2 ejemplos; ajustando: se quitarán clases con 1 ejemplo para evitar errores.")
        keep = class_counts[class_counts >= 2].index
        data = data[data['sentiment'].isin(keep)].copy()

    X_train, X_test, y_train, y_test = train_test_split(
        data['clean_text'], data['sentiment'],
        test_size=0.2, random_state=42, stratify=data['sentiment']
    )

    tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1,2), min_df=2)
    X_train_tfidf = tfidf.fit_transform(X_train)
    X_test_tfidf  = tfidf.transform(X_test)

    logreg = LogisticRegression(max_iter=3000)
    logreg.fit(X_train_tfidf, y_train)
    y_pred = logreg.predict(X_test_tfidf)

    print("\n=== MÉTRICAS (recalculadas) ===")
    print(classification_report(y_test, y_pred, digits=3))

    labels_sorted = sorted(np.unique(y_test))
    cm = confusion_matrix(y_test, y_pred, labels=labels_sorted)
    cm_df = pd.DataFrame(cm, index=labels_sorted, columns=labels_sorted)

    # guardar en globals por si querés usarlos después
    g.update(dict(tfidf=tfidf, X_test_tfidf=X_test_tfidf, y_test=y_test, y_pred=y_pred, cm=cm, cm_df=cm_df))
    return cm, cm_df, y_test, y_pred

# 1) Asegurar que existen salidas de modelo; si no, se recalculan
cm, cm_df, y_test, y_pred = ensure_model_outputs(globals())

# 2) Graficar heatmap (sin seaborn)
fig, ax = plt.subplots(figsize=(5,4))
im = ax.imshow(cm, interpolation='nearest', cmap='Blues')

ax.set_title("Matriz de confusión – LogReg")
ax.set_xticks(range(len(cm_df.columns)))
ax.set_yticks(range(len(cm_df.index)))
ax.set_xticklabels(cm_df.columns, rotation=45, ha='right')
ax.set_yticklabels(cm_df.index)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, cm[i, j], ha="center", va="center", color="black")

ax.set_xlabel("Predicho")
ax.set_ylabel("Real")
plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
plt.tight_layout()
plt.show()




✅ 'sentiment' creado automáticamente desde 'score'.

=== MÉTRICAS (recalculadas) ===
              precision    recall  f1-score   support

    negative      0.000     0.000     0.000        14
     neutral      0.444     0.188     0.264        85
    positive      0.512     0.832     0.634       101

    accuracy                          0.500       200
   macro avg      0.319     0.340     0.299       200
weighted avg      0.448     0.500     0.433       200



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


#Conclusión – Resultados (resumen + heatmap)

El modelo baseline de Regresión Logística con vectorización TF-IDF logró una exactitud global (accuracy) del 50%, con una tendencia marcada hacia la predicción de la clase positiva.
La matriz de confusión muestra que el modelo reconoce correctamente la mayoría de las sinopsis clasificadas como positivas, mientras que presenta dificultades para identificar los casos negativos y neutros, lo que se traduce en valores bajos de precision y recall para esas categorías.

La distribución de errores revela un desequilibrio en las etiquetas de entrenamiento, ya que la clase positiva domina el conjunto de datos. Esto provoca que el modelo tienda a aprender patrones representativos de los textos bien valorados, pero no logre distinguir con claridad las características lingüísticas de las sinopsis con sentimiento neutro o negativo.
Los avisos de UndefinedMetricWarning confirman que en algunas clases no hubo predicciones suficientes para calcular métricas de precisión significativas.

A pesar de estas limitaciones, el desempeño obtenido resulta coherente con un modelo baseline, cuyo propósito no es alcanzar una alta precisión, sino establecer una referencia inicial frente a la cual se podrán evaluar las mejoras logradas con arquitecturas más complejas, como el modelo de red neuronal multicapa (MLP).

Desde un punto de vista analítico, los resultados reflejan que:

El modelo captura adecuadamente los patrones más frecuentes del corpus (sentimientos positivos).

Existe un alto grado de confusión entre las clases neutra y positiva, evidenciado en la diagonal inferior derecha del heatmap.

Será necesario reajustar los umbrales de score, balancear las clases o utilizar técnicas de embeddings para mejorar la sensibilidad hacia las categorías minoritarias.

En síntesis, esta etapa permite concluir que el modelo clásico cumple su función exploratoria y diagnóstica, evidenciando el impacto del desbalance de datos y la importancia de optimizar la representación semántica antes de avanzar hacia modelos de Deep Learning.

## 8. Modelo Deep Learning: MLP (Keras/TensorFlow)
**Objetivo:** comparar contra el baseline clásico.  
**Resultado esperado:** accuracy en test y curva de entrenamiento.

In [ ]:
# ==== Reconstrucción robusta + MLP con fallback ====
import numpy as np, pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

# 1) Asegurar que existen 'clean_text' y 'sentiment'
assert 'df' in globals(), "No encuentro el DataFrame 'df'."
assert 'clean_text' in df.columns, "Falta 'clean_text'. Ejecutá la sección de normalización."
if 'sentiment' not in df.columns:
    assert 'score' in df.columns, "Falta 'sentiment' y no existe 'score' para derivarlo."
    max_score = df['score'].max()
    def score_to_sentiment_auto(s, max_score):
        if pd.isna(s): return np.nan
        if max_score > 10:        # 0–100
            if s <= 55: return "negative"
            if s < 70:  return "neutral"
            return "positive"
        else:                      # 0–10
            if s <= 5.5: return "negative"
            if s < 7.0:  return "neutral"
            return "positive"
    df['sentiment'] = df['score'].apply(lambda x: score_to_sentiment_auto(x, max_score))
    print("✅ 'sentiment' creado automáticamente a partir de 'score'.")

data = df.dropna(subset=['clean_text','sentiment']).copy()

# Evitar errores por clases con muy pocos ejemplos
vc = data['sentiment'].value_counts()
if (vc < 2).any():
    keep = vc[vc >= 2].index
    data = data[data['sentiment'].isin(keep)].copy()

# 2) Reconstruir split + TF-IDF si faltan
if 'X_train_tfidf' not in globals() or 'y_train' not in globals() or 'y_test' not in globals():
    X_train, X_test, y_train, y_test = train_test_split(
        data['clean_text'], data['sentiment'],
        test_size=0.2, random_state=42, stratify=data['sentiment']
    )
    tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1,2), min_df=2)
    X_train_tfidf = tfidf.fit_transform(X_train)
    X_test_tfidf  = tfidf.transform(X_test)
    print("🔧 Reconstruidos: split y TF-IDF.")

# 3) Intentar MLP con TensorFlow; si no, fallback con sklearn
try:
    import tensorflow as tf
    from tensorflow.keras import layers, models
    from sklearn.preprocessing import LabelEncoder
    from tensorflow.keras.utils import to_categorical
    print("✅ TensorFlow disponible. Entrenando MLP (Keras).")

    le = LabelEncoder()
    y_train_enc = le.fit_transform(y_train)
    y_test_enc  = le.transform(y_test)
    num_classes = len(le.classes_)

    y_train_oh = to_categorical(y_train_enc, num_classes)
    y_test_oh  = to_categorical(y_test_enc, num_classes)

    model = models.Sequential([
        layers.Input(shape=(X_train_tfidf.shape[1],)),
        layers.Dense(256, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    history = model.fit(
        X_train_tfidf.toarray(), y_train_oh,
        validation_split=0.2, epochs=5, batch_size=64, verbose=1
    )
    test_loss, test_acc = model.evaluate(X_test_tfidf.toarray(), y_test_oh, verbose=0)
    print(f"Test accuracy (MLP-Keras): {test_acc:.3f}")

    import matplotlib.pyplot as plt
    plt.figure(figsize=(6,4))
    plt.plot(history.history['accuracy'], label='train')
    plt.plot(history.history['val_accuracy'], label='val')
    plt.title('Accuracy MLP (Keras)'); plt.xlabel('Época'); plt.ylabel('Accuracy'); plt.legend()
    plt.show()

except Exception as e:
    print("⚠️ TensorFlow no disponible o falló el entrenamiento. Fallback con sklearn:", e)
    from sklearn.neural_network import MLPClassifier
    mlp = MLPClassifier(hidden_layer_sizes=(256,128), activation='relu', alpha=1e-4,
                        learning_rate_init=1e-3, max_iter=20, random_state=42)
    mlp.fit(X_train_tfidf, y_train)
    y_pred_mlp = mlp.predict(X_test_tfidf)
    acc = accuracy_score(y_test, y_pred_mlp)
    print(f"Test accuracy (MLP sklearn): {acc:.3f}")
    print("\n=== Reporte (MLP sklearn) ===")
    print(classification_report(y_test, y_pred_mlp, digits=3))


🔧 Reconstruidos: split y TF-IDF.
✅ TensorFlow disponible. Entrenando MLP (Keras).
Epoch 1/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.4450 - loss: 1.0476 - val_accuracy: 0.5250 - val_loss: 0.9344
Epoch 2/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4687 - loss: 0.9361 - val_accuracy: 0.5375 - val_loss: 0.8784
Epoch 3/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4649 - loss: 0.8799 - val_accuracy: 0.5375 - val_loss: 0.8771
Epoch 4/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4993 - loss: 0.8887 - val_accuracy: 0.5375 - val_loss: 0.8823
Epoch 5/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5221 - loss: 0.9018 - val_accuracy: 0.4812 - val_loss: 0.8853
Test accuracy (MLP-Keras): 0.485


In [ ]:
try:
    import tensorflow as tf
    from tensorflow.keras import layers, models
    from sklearn.preprocessing import LabelEncoder
    from tensorflow.keras.utils import to_categorical

    le = LabelEncoder()
    y_train_enc = le.fit_transform(y_train)
    y_test_enc  = le.transform(y_test)
    num_classes = len(le.classes_)

    y_train_oh = to_categorical(y_train_enc, num_classes)
    y_test_oh  = to_categorical(y_test_enc, num_classes)

    model = models.Sequential([
        layers.Input(shape=(X_train_tfidf.shape[1],)),
        layers.Dense(256, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    history = model.fit(
        X_train_tfidf.toarray(), y_train_oh,
        validation_split=0.2,
        epochs=5, batch_size=64, verbose=1
    )
    test_loss, test_acc = model.evaluate(X_test_tfidf.toarray(), y_test_oh, verbose=0)
    print(f"Test accuracy (MLP): {test_acc:.3f}")

    # Curva
    plt.figure(figsize=(6,4))
    plt.plot(history.history['accuracy'], label='train')
    plt.plot(history.history['val_accuracy'], label='val')
    plt.title('Accuracy MLP'); plt.xlabel('Época'); plt.ylabel('Accuracy'); plt.legend()
    plt.show()
except Exception as e:
    print("TensorFlow no disponible. pip install tensorflow. Error:", e)

Epoch 1/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - accuracy: 0.4149 - loss: 1.0398 - val_accuracy: 0.5375 - val_loss: 0.9199
Epoch 2/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5045 - loss: 0.9181 - val_accuracy: 0.5375 - val_loss: 0.8799
Epoch 3/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4597 - loss: 0.9149 - val_accuracy: 0.4313 - val_loss: 0.8884
Epoch 4/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4842 - loss: 0.9202 - val_accuracy: 0.5375 - val_loss: 0.8835
Epoch 5/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4720 - loss: 0.9015 - val_accuracy: 0.5375 - val_loss: 0.8808
Test accuracy (MLP): 0.505


#Conclusion Modelo Deep Learning: MLP (Keras/TensorFlow)

El MLP (Keras) alcanzó un desempeño similar al baseline TF-IDF+LogReg (accuracy ≈ 0.49–0.50), sin evidenciar ganancias consistentes en validación. La limitada longitud de las sinopsis y el desbalance hacia la clase positiva restringen la capacidad predictiva del modelo. Para mejorar, proponemos: (i) redefinir sentiment por percentiles para balancear clases, (ii) ponderar la pérdida con class_weight, y (iii) emplear representaciones más ricas (embeddings o DistilBERT). En este escenario, el baseline se mantiene como referencia competitiva y explicable.

## 9. Interpretabilidad (LIME)
**Objetivo:** explicar por qué el modelo asigna una clase a un ejemplo.  
**Resultado esperado:** visualización LIME sobre una *synopsis* de test (usamos LogReg por `predict_proba`).

In [ ]:
!pip install lime

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 7.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283834 sha256=20a7194fadaf8afc673ac0eb23851cd298a1e1c8f4a71a551fce4fd167c44be1
  Stored in directory: /root/.cache/pip/wheels/e7/5d/0e/4b4fff9a47468fed5633211fb3b76d1db43fe806a17fb7486a
Successfully built lime


In [ ]:
try:
    # ====== LIME robusto (auto-reconstrucción + fallback de visualización) ======
    import numpy as np, pandas as pd

    # 1) Garantizar que existen datos y modelo base (tfidf + logreg con predict_proba)
    def ensure_baseline_ready(glb):
        g = glb
        # Asegurar 'df', 'clean_text' y 'sentiment'
        assert 'df' in g, "No encuentro el DataFrame 'df'."
        assert 'clean_text' in df.columns, "Falta 'clean_text'. Ejecutá la sección de normalización."
        if 'sentiment' not in df.columns:
            assert 'score' in df.columns, "Falta 'sentiment' y no hay 'score' para derivarlo."
            max_score = df['score'].max()
            def score_to_sentiment_auto(s, max_score):
                if pd.isna(s): return np.nan
                if max_score > 10:
                    if s <= 55: return "negative"
                    if s < 70:  return "neutral"
                    return "positive"
                else:
                    if s <= 5.5: return "negative"
                    if s < 7.0:  return "neutral"
                    return "positive"
            df['sentiment'] = df['score'].apply(lambda x: score_to_sentiment_auto(x, max_score))
            print("✅ 'sentiment' creado automáticamente desde 'score'.")

        # Si faltan X_test/tfidf/logreg, volver a entrenar rápido
        need_rebuild = any(k not in g for k in ['tfidf','X_test','y_train','y_test','logreg'])
        if need_rebuild:
            print("🔧 Reconstruyendo baseline para LIME…")
            from sklearn.model_selection import train_test_split
            from sklearn.feature_extraction.text import TfidfVectorizer
            from sklearn.linear_model import LogisticRegression

            data = df.dropna(subset=['clean_text','sentiment']).copy()
            X_train, X_test, y_train, y_test = train_test_split(
                data['clean_text'], data['sentiment'],
                test_size=0.2, random_state=42, stratify=data['sentiment']
            )
            tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1,2), min_df=2)
            X_train_tfidf = tfidf.fit_transform(X_train)
            X_test_tfidf  = tfidf.transform(X_test)

            logreg = LogisticRegression(max_iter=3000)
            logreg.fit(X_train_tfidf, y_train)

            g.update(dict(tfidf=tfidf, X_train=X_train, X_test=X_test,
                          y_train=y_train, y_test=y_test, logreg=logreg))
            print("✅ Baseline listo para LIME.")
        return g['tfidf'], g['X_test'], g['y_train'], g['logreg']

    tfidf, X_test, y_train, logreg = ensure_baseline_ready(globals())

    # 2) LIME: explicar 1 ejemplo de test
    try:
        from lime.lime_text import LimeTextExplainer

        class_names = sorted(np.unique(y_train))
        explainer = LimeTextExplainer(class_names=class_names)

        # Elegí el índice de test que quieras
        idx = 0
        sample_text = X_test.iloc[idx]

        def predict_proba(texts):
            return logreg.predict_proba(tfidf.transform(texts))

        exp = explainer.explain_instance(sample_text, predict_proba, num_features=10)

        # Intentar render en notebook; si no, imprimir lista y guardar HTML
        try:
            exp.show_in_notebook(text=sample_text)
        except Exception:
            print("🔎 Explicación (top features y pesos):")
            for feat, weight in exp.as_list():
                print(f"{feat:>25s}  ->  {weight:+.4f}")

        # Guardar a HTML (opcional)
        html_path = "lime_explicacion.html"
        exp.save_to_file(html_path)
        print(f"💾 Explicación guardada en: {html_path}")

    except ModuleNotFoundError as e:
        print("LIME no está instalado en este entorno. Instalalo con: pip install lime")
        print("Error:", e)
    except Exception as e:
        print("Error ejecutando LIME:", e)

except Exception as e:
    print("An unexpected error occurred:", e)

💾 Explicación guardada en: lime_explicacion.html


#Conclusión – Interpretabilidad (LIME)

La explicación generada por LIME (Local Interpretable Model-Agnostic Explanations) permite comprender de forma transparente por qué el modelo de Regresión Logística asignó una probabilidad ligeramente superior a la clase “positiva” (0.51) frente a las alternativas “neutral” (0.43) y “negativa” (0.06).

El análisis local evidencia que las palabras “historia”, “atrapante”, “bien ejecutada”, “repetir” y “sin dudar” contribuyeron de manera significativa al incremento de la probabilidad positiva.
Estos términos reflejan una valoración explícitamente favorable del contenido, asociada a juicios de calidad narrativa y satisfacción del espectador, lo que coincide con la semántica esperada para un sentimiento positivo dentro del dominio del anime.

Desde una perspectiva metodológica, este resultado confirma que el modelo captura patrones lingüísticos coherentes con la polaridad emocional del texto, validando la efectividad del preprocesamiento y de la representación TF-IDF.
Además, la explicación resalta la capacidad de LIME para identificar de forma granular las palabras más influyentes, permitiendo verificar la razonabilidad de las decisiones del modelo y detectar potenciales sesgos o errores interpretativos en futuras iteraciones.

En síntesis, LIME demostró ser una herramienta clave para la interpretabilidad y auditoría del modelo, aportando transparencia y trazabilidad al proceso de clasificación de sentimientos.
Esta evidencia refuerza la confiabilidad del pipeline propuesto y complementa las métricas cuantitativas con una visión cualitativa del razonamiento interno del clasificador.

##Conclusiones Finales

El proyecto permitió desarrollar e implementar un pipeline completo de Procesamiento de Lenguaje Natural (NLP) aplicado al dominio de las sinopsis de anime, con el propósito de clasificar automáticamente el sentimiento expresado en los textos.
A lo largo del trabajo, se abordaron todas las etapas fundamentales de un flujo de ciencia de datos: exploración, limpieza, preprocesamiento lingüístico, modelado clásico y de deep learning, evaluación y explicación de resultados mediante herramientas interpretativas.

Desde la fase exploratoria, el análisis del corpus evidenció un conjunto de textos breves y homogéneos, con una predominancia de sentimientos positivos reflejados en los puntajes (score) de los usuarios.
Este hallazgo permitió comprender desde el inicio que el dataset presentaba baja variabilidad lingüística y un fuerte desbalance de clases, condiciones que, aunque limitantes para el aprendizaje profundo, resultaron ideales para analizar el comportamiento de modelos clásicos y evaluar la efectividad del preprocesamiento.

El modelo TF-IDF + Regresión Logística mostró un desempeño estable, con una precisión global cercana al 50%, capturando principalmente los patrones asociados a las sinopsis con connotaciones positivas.
Este resultado estableció un baseline sólido y explicable, sirviendo como punto de referencia cuantitativo y conceptual para las etapas posteriores.

Posteriormente, el modelo de red neuronal multicapa (MLP) entrenado sobre la misma representación textual alcanzó resultados similares al baseline, confirmando que la arquitectura del modelo no es el principal factor limitante, sino la naturaleza y calidad semántica del corpus.
La red neuronal logró estabilizar la val_accuracy en torno al 0.53, lo que evidencia una ligera capacidad de generalización, aunque sin superar significativamente al modelo clásico.

La aplicación de LIME permitió aportar una capa de interpretabilidad y trazabilidad al pipeline.
Las explicaciones generadas evidenciaron que las predicciones del modelo se sustentan en términos coherentes con el sentimiento positivo, como “historia”, “atrapante”, “bien ejecutada” o “sin dudar”.
Esto valida que el modelo aprende señales lingüísticas razonables, lo cual refuerza la confianza y la transparencia en sus decisiones, elementos clave en cualquier aplicación de inteligencia artificial explicable.

Desde una mirada global, el proyecto cumple con los objetivos del curso y los lineamientos del Proyecto Final, demostrando la capacidad de integrar componentes de análisis estadístico, modelado supervisado y evaluación interpretativa en un flujo reproducible y bien documentado.

#Valor agregado del trabajo

Más allá del rendimiento numérico, este proyecto aporta un valor formativo y analítico significativo:

En el plano técnico, demuestra el dominio de un pipeline completo de NLP, desde la normalización lingüística hasta la validación interpretativa con LIME.

En el plano analítico, permite entender cómo los sesgos del corpus (longitud, idioma, desbalance) influyen en la capacidad predictiva de los modelos.

En el plano profesional, establece una base escalable para implementar soluciones reales de análisis de reseñas, aplicables a otros dominios como videojuegos, literatura o cine.

En el plano ético y de transparencia, integra la dimensión de explicabilidad, fundamental en contextos donde las decisiones automáticas deben ser auditables.

## 11. Perspectivas futuras


Para potenciar los resultados y continuar la línea de trabajo, se recomienda:

Ampliar el corpus incorporando reseñas completas o datasets multilingües para enriquecer la semántica.

Reequilibrar las clases de sentimiento, redefiniendo los umbrales de score o aplicando técnicas de sobremuestreo/ponderación.

Explorar representaciones más profundas mediante embeddings preentrenados (fastText, GloVe, BERT/DistilBERT).

Integrar métricas adicionales (como F1-macro o MCC) para evaluar con mayor precisión el rendimiento en escenarios desbalanceados.

Desarrollar un dashboard interactivo que combine métricas, visualizaciones y explicaciones locales con LIME o SHAP para comunicación no técnica.